name: Static Site CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Run HTML Lint (optional)
      run: |
        npm install -g htmlhint
        htmlhint "**/*.html" || true

    - name: Done
      run: echo "CI pipeline executed successfully."
